### ISSUE TITLE
How to compute the `mac` and `clock` values 

### ISSUE THREAD

**Issue by Sim4n6** [Lupin-Holmes/sandwich#3]
I am facing a similar case of UUIDv1 use, I've stumbled upon the sandwich attack. 

However, I noticed that for the attack to be successful, the attacker needs to guess the `clock` value and the `mac` address, besides the timestamp range. 

The values of `clock` and `mac` are retrieved from [sandwich.rb#L4](https://github.com/Lupin-Holmes/sandwich/blob/5cffcb8b950b4a2adce87dd16ce291aaf6258571/sandwich.rb#L4) the initial lower limit uuid. 

Does this mean the `clock` and  `mac` were fixed in your target? or am I missing something related to the values of `mac` and the `clock`

Regards
@sim4n6

**Comment by Roni-Carta** [comment]
Hi @Sim4n6, 

I hope you're doing great today? 

>  the attacker needs to guess the clock value and the mac address, besides the timestamp range.

Normally this value is always the same for a machine. If it's a UUIDv1 and you don't have the same `mac` or `clock` values, it's probably because different machines are generating the V1s (we had a target with a Kubernetes with 30 different pods that were computing the V1s) or it's a custom implementation. You can read more on the UUIDv1 documentation:

- Clock: https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.5
- Mac: https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.6

You can know more about how we did the full exploitation on the following links:

- https://www.youtube.com/watch?v=Wgo3bGv6KqI
- https://www.landh.tech/blog/20230811-sandwich-attack

Hopefully it answers your question :) 

Have a great day, 

Cheers ! 

Lupin

**Comment by Sim4n6** [comment]
Thank you very much.

**Comment by Sim4n6** [comment]
Sorry to reopen the issue, but in the context of your attack 30 pods , meant having only 30sh possible MAC addresses ? 

I've generated at least 100 V1s. It is possible that the `mac` are random ?

**Comment by Sim4n6** [comment]
Never mind I 'm definetly facing a cuztom generated nodes
